// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddListItemInput struct {
	IDAnyOf []int `json:"idAnyOf"`
}

type AddListItemResult struct {
	Item *Item `json:"item"`
}

type FileData struct {
	Name string `json:"name"`
	Size string `json:"size"`
	Mime string `json:"mime"`
}

type FileInfoResult struct {
	File *FileData `json:"file"`
}

type FilesInfoResult struct {
	Files []*FileData `json:"files"`
}

type Item struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type ListItemsInput struct {
	IDAnyOf []int `json:"idAnyOf"`
}

type ListItemsResult struct {
	Items []*Item `json:"items"`
}

type UploadFileResult struct {
	File *FileData `json:"file"`
}

type UploadFilesResult struct {
	Files []*FileData `json:"files"`
}
