// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FileData struct {
	Name string `json:"name"`
	Size string `json:"size"`
	Mime string `json:"mime"`
}

type FileInfoResult struct {
	File *FileData `json:"file"`
}

type FilesInfoResult struct {
	Files []*FileData `json:"files"`
}

type UploadFileResult struct {
	File *FileData `json:"file"`
}

type UploadFilesResult struct {
	Files []*FileData `json:"files"`
}
